### ISSUE TITLE
Opening link on the same page

### ISSUE THREAD

**Issue by karimbakhshamiry** [Faizakarimi/odin_recipes#1]
https://github.com/Faizakarimi/odin_recipes/blame/ee22b520798b86ec340833eedd0a6513af04daff/index.html#L11C19-L11C19

It is recommended to open links in a new page when the link goes to another website, but opening the link of our own website should open it on the same page. So, you may want to remove the `target="_blank"`.

**Comment by Faizakarimi** [comment]
Dear Amiry, 
Thank you for your feedback. I updated the files. Please kindly check again.
