### ISSUE TITLE
Broken Links and Wrong File Path

### ISSUE THREAD

**Issue by karimbakhshamiry** [Faizakarimi/odin_recipes#2]
https://github.com/Faizakarimi/odin_recipes/blob/ee22b520798b86ec340833eedd0a6513af04daff/index.html#L12C1-L12C99

1. The links are broke. When I click on the second and third recipe, it does not take me anywhere. Images are also not shown because of the the wrong file path.
Watch this video on file path, and then fix the links please.

https://youtu.be/hxto_sRZsBg

2. It is also recommended to open new link in a new tab only if it is from another website. If it is from your won website, then, do not open it in a new tab. So you may want to remove `target="_blank"` from link in your index file.

**Comment by Faizakarimi** [comment]
Dear Amiry, 
Thank you for your feedback. I updated the files. Please kindly check again.
